# A sample Gemfile
source "http://rubygems.org"


gem "sass", "3.4.19"
gem "sass-globbing", "~> 1.1.1"
gem "sassy-maps"
gem "compass", "~> 1.0.3"
gem "modular-scale", "~> 2.1.1"
gem "compass-normalize"
gem "compass-validator"
gem "compass-rgbapng"
gem "toolkit"
gem "chunky_png"
gem "breakpoint"
gem "susy"
