search_api_solr_multilingual.solr_field_type.*:
  type: config_entity
  label: 'Solr Field Type Config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    managed_schema:
      type: boolean
      label: 'Managed schema'
    minimum_solr_version:
      type: string
      label: 'The minimum version the Solr server'
    field_type_language_code:
      type: string
      label: 'The language targeted by this Solr Field Type'
    domains:
      type: sequence
      sequence:
        type: string
    field_type:
      type: mapping
      mapping:
        name:
          type: string
          label: 'The Solr field name'
        class:
          type: string
          label: 'The Solr field type'
        positionIncrementGap:
          type: integer
          label: 'Solr field attribute positionIncrementGap'
        analyzers:
          type: sequence
          sequence:
            type: mapping
            mapping:
              type:
                type: string
                label: 'The analyzer type'
              charFilters:
                type: sequence
                nullable : true
                sequence:
                  type: mapping
                  mapping:
                    class:
                      type: string
                      label: 'The char filter class'
                    mapping:
                      type: string
                      label: 'The char filter mapping file name'
                      nullable: true
              tokenizer:
                type: mapping
                mapping:
                  class:
                    type: string
                    label: 'The tokenizer class'
              filters:
                type: sequence
                sequence:
                  type: mapping
                  mapping:
                    class:
                      type: string
                      label: 'The filter class'
                    catenateNumbers:
                      type: integer
                      label: 'WordDelimiterFilter::catenateNumbers'
                      nullable: true
                    generateNumberParts:
                      type: integer
                      label: 'WordDelimiterFilter::generateNumberParts'
                      nullable: true
                    protected:
                      type: string
                      label: 'WordDelimiterFilter:: SnowballPorterFilter::protected'
                      nullable: true
                    splitOnCaseChange:
                      type: integer
                      label: 'WordDelimiterFilter::splitOnCaseChange'
                      nullable: true
                    splitOnNumerics:
                      type: integer
                      label: 'WordDelimiterFilter::splitOnNumerics'
                      nullable: true
                    generateWordParts:
                      type: integer
                      label: 'WordDelimiterFilter::generateWordParts'
                      nullable: true
                    preserveOriginal:
                      type: integer
                      label: 'WordDelimiterFilter::preserveOriginal'
                      nullable: true
                    catenateAll:
                      type: integer
                      label: 'WordDelimiterFilter::catenateAll'
                      nullable: true
                    catenateWords:
                      type: integer
                      label: 'WordDelimiterFilter::catenateWords'
                      nullable: true
                    stemEnglishPossessive:
                      type: integer
                      label: 'WordDelimiterFilter::stemEnglishPossessive'
                      nullable: true
                    min:
                      type: integer
                      label: 'LengthFilter::min'
                      nullable: true
                    max:
                      type: integer
                      label: 'LengthFilter::max'
                      nullable: true
                    dictionary:
                      type: string
                      label: 'DictionaryCompoundWordTokenFilter::dictionary'
                      nullable: true
                    minWordSize:
                      type: integer
                      label: 'DictionaryCompoundWordTokenFilter::minWordSize'
                      nullable: true
                    minSubwordSize:
                      type: integer
                      label: 'DictionaryCompoundWordTokenFilter::minSubwordSize'
                      nullable: true
                    maxSubwordSize:
                      type: integer
                      label: 'DictionaryCompoundWordTokenFilter::maxSubwordSize'
                      nullable: true
                    onlyLongestMatch:
                      type: boolean
                      label: 'DictionaryCompoundWordTokenFilter::onlyLongestMatch'
                      nullable: true
                    ignoreCase:
                      type: boolean
                      label: 'StopFilter:: SynonymFilter::ignoreCase'
                      nullable: true
                    words:
                      type: string
                      label: 'StopFilter::words'
                      nullable: true
                    language:
                      type: string
                      label: 'SnowballPorterFilter::language'
                      nullable: true
                    synonyms:
                      type: string
                      label: 'SynonymFilter::synonyms'
                      nullable: true
                    expand:
                      type: boolean
                      label: 'SynonymFilter:: ManagedSynonymFilter::expand'
                      nullable: true
                    managed:
                      type: string
                      label: 'ManagedStopFilter::managed'
                      nullable: true
                    articles:
                      type: string
                      label: 'ElisionFilter::articles'
                      nullable: true
                    minGramSize:
                      type: integer
                      label: 'EdgeNGramFilterFactory::minGramSize'
                      nullable: true
                    maxGramSize:
                      type: integer
                      label: 'EdgeNGramFilterFactory::maxGramSize'
                      nullable: true
    text_files:
      type: mapping
      mapping:
        stopwords:
          type: string
          label: 'Stop words'
        protwords:
          type: string
          label: 'Protected words'
        accents:
          type: string
          label: 'Accent char mapping'
        synonyms:
          type: string
          label: 'Synonym words'
        nouns:
          type: string
          label: 'Nouns'
